### ISSUE TITLE
its not givibng promos

### ISSUE THREAD

**Issue by Jonybieleber828** [sexfrance/Webtoon-Promo-Gen#1]
its just making acc

**Comment by sexfrance** [comment]
It is normal.

First of all webtoons x discord promos finished the 25th December it doesn't work anymore (but you can still use it in the future if they do the promo again)

Second of all, webtoons randomly sends the discord promotion in a 72h (sometimes more) hour span that's  why there is a server, to intercept the emails and save the promos

**Comment by Jonybieleber828** [comment]
You have stream lab promo gen ?

**Comment by sexfrance** [comment]
Yes I made one with my partner but I won’t release it on GitHub right now as it is worth over 600$

**Comment by Jonybieleber828** [comment]
Like I have one but need help in email thing

**Comment by sexfrance** [comment]
Join the discord https://discord.gg/TnBgfb6H I can help you there
